
// (c) 2025 Kazuki Kohzuki

namespace EnumSerializer.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class AttributesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("EnumSerializableAttribute.g.cs", EnumSerializableSource);
            context.AddSource("ExtensionMethods.g.cs", ExtensionMethodsSource);
            context.AddSource("SerializeValueAttribute.g.cs", SerializeValueSource);
            context.AddSource("DefaultSerializeValueAttribute.g.cs", DefaultSerializeValueSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    internal const string Namespace = "EnumSerializer";
    internal const string EnumSerializableName = "EnumSerializableAttribute";
    internal const string SerializeValueName = "SerializeValueAttribute";
    internal const string DefaultSerializeValueName = "DefaultSerializeValueAttribute";

    // lang=C#
    private const string EnumSerializableSource = """
// <auto-generated/>

#nullable enable

namespace EnumSerializer
{
    /// <summary>
    /// Specifies that the enum is serializable with the specified target attributes.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = false, AllowMultiple = true)]
    internal sealed class EnumSerializableAttribute : global::System.Attribute
    {
        /// <summary>
        /// Gets the target attributes for serialization.
        /// </summary>
        public global::System.Type Target { get; }

        /// <summary>
        /// Gets or sets a value indicating whether the serialization should be case-sensitive.
        /// </summary>
        /// <value><see langword="true"/> if the serialization should be case-sensitive; otherwise, <see langword="false"/>. The default value is <see langword="true"/>.</value>
        public bool CaseSensitive { get; set; } = true;

        /// <summary>
        /// Gets or sets the name of the extension class to be generated for enum serialization.
        /// </summary>
        /// <remarks>
        /// If <see langword="null"/>, the extension class will be generated with the default name with suffix to avoid name conflicts.
        /// If specified, the extension class will be generated with the specified name without any modification and the generator will not check for name conflicts.
        /// </remarks>
        public string? ExtensionClassName { get; set; } = null;

        /// <summary>
        /// Gets or sets the extension methods to be generated for enum serialization.
        /// </summary>
        public global::EnumSerializer.ExtensionMethods Methods { get; set; } = global::EnumSerializer.ExtensionMethods.All;

        /// <summary>
        /// Initializes a new instance of the <see cref="EnumSerializableAttribute"/> class.
        /// </summary>
        /// <param name="target">Target attribute for serialization.</param>
        internal EnumSerializableAttribute(global::System.Type target)
        {
            this.Target = target;
        }
    }
}

""";

    // lang=C#
    private const string ExtensionMethodsSource = """
// <auto-generated/>

namespace EnumSerializer
{
    /// <summary>
    /// Specifies the extension methods to be generated for enum serialization.
    /// </summary>
    [global::System.Flags]
    internal enum ExtensionMethods
    {
        /// <summary>
        /// No extension methods will be generated.
        /// </summary>
        None = 0,

        /// <summary>
        /// The <c>ToString</c> extension method will be generated, allowing conversion of enum members to their serialized string representations.
        /// </summary>
        ToString = 1 << 0,

        /// <summary>
        /// The <c>TryParse</c> extension method will be generated, allowing parsing of serialized string representations back to enum members.
        /// </summary>
        TryParse = 1 << 1,

        /// <summary>
        /// Both <c>ToString</c> and <c>TryParse</c> extension methods will be generated.
        /// </summary>
        All = ToString | TryParse,
    }
}

""";

    // lang=C#-test
    private const string SerializeValueSource = """
// <auto-generated/>

#nullable enable

namespace EnumSerializer
{
    /// <summary>
    /// Represents a serialized value of an enum member.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = true)]
    internal abstract class SerializeValueAttribute : global::System.Attribute
    {
        /// <summary>
        /// Gets the serialized value.
        /// </summary>
        internal string Value { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="SerializeValueAttribute"/> class.
        /// </summary>
        /// <param name="value">The serialized value.</param>
        internal SerializeValueAttribute(string value)
        {
            this.Value = value;
        }
    }
}

""";

    // lang=C#-test
    private const string DefaultSerializeValueSource = """
// <auto-generated/>

#nullable enable

namespace EnumSerializer
{
    /// <summary>
    /// Represents a default serialized value of an enum member.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    internal class DefaultSerializeValueAttribute : global::EnumSerializer.SerializeValueAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultSerializeValueAttribute"/> class.
        /// </summary>
        internal DefaultSerializeValueAttribute(string value) : base(value) {}
    }
}

""";
} // internal sealed class AttributesGenerator : IIncrementalGenerator
