
// (c) 2025-2026 Kazuki Kohzuki

using System.Collections.Generic;
using System.Threading;

namespace EnumSerializer.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed partial class SerializerGenerator : IIncrementalGenerator
{
    private const int MaxStackAllocLength = 256;

    private const string AttributeFullName = $"{AttributesGenerator.Namespace}.{AttributesGenerator.EnumSerializableName}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var canUseSpanProvider = context.CompilationProvider.Select(CheckFeaturesAvailability);

        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            static (node, token) => node is EnumDeclarationSyntax,
            static (context, token) => context
        );

        var combined = sources.Combine(canUseSpanProvider);
        context.RegisterSourceOutput(combined, Execute);
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private static GenerationMode CheckFeaturesAvailability(Compilation compilation, CancellationToken cancellationToken)
    {
        if (compilation is not CSharpCompilation csharpCompilation) return GenerationMode.StringFallback;

        // C# 8.0 or later is required for `using` pattern with ref struct
        if (csharpCompilation.LanguageVersion < LanguageVersion.CSharp8) return GenerationMode.StringFallback;

        var readOnlySpanType = compilation.GetTypeByMetadataName("System.ReadOnlySpan`1");
        if (readOnlySpanType == null) return GenerationMode.StringFallback;

        var memoryExtensionsType = compilation.GetTypeByMetadataName("System.MemoryExtensions");
        if (memoryExtensionsType == null) return GenerationMode.StringFallback;

        var hasToLowerInvariantSpan = false;
        foreach (var member in memoryExtensionsType.GetMembers("ToLowerInvariant"))
        {
            if (member is IMethodSymbol method && method.Parameters.Length == 2)
            {
                var p1 = method.Parameters[0].Type.OriginalDefinition;
                var p2 = method.Parameters[1].Type.OriginalDefinition;

                if (p1.Name == "ReadOnlySpan" && p2.Name == "Span")
                {
                    hasToLowerInvariantSpan = true;
                    break;
                }
            }
        }

        if (!hasToLowerInvariantSpan)
            return GenerationMode.StringFallback;

        if (csharpCompilation.LanguageVersion >= LanguageVersion.CSharp11)
            return GenerationMode.OptimizedSpanWithPatternMatching;
        else
            return GenerationMode.OptimizedSpanWithIfElse;
    } // private static bool CheckFeaturesAvailability (Compilation, CancellationToken)

    private static void Execute(SourceProductionContext context, (GeneratorAttributeSyntaxContext Left, GenerationMode Right) provider)
    {
        var type = provider.Left;
        var generationMode = provider.Right;

        var typeSymbol = (INamedTypeSymbol)type.TargetSymbol;

        var builder = new StringBuilder();
        builder.AppendLine("""
// <auto-generated/>
""");

        if (generationMode >= GenerationMode.OptimizedSpanWithIfElse)
        {
            // C# 8.0 or later
            builder.AppendLine();
            builder.AppendLine("#nullable enable");
        }

        try
        {
            var attrs = type.Attributes.Where(a => a.AttributeClass.GetFullName() == AttributeFullName);
            var args =
                type.Attributes.Where(a => a.AttributeClass.GetFullName() == AttributeFullName)
                               .Select(GetEnumSerializationInfo)
                               .OfType<EnumSerializationInfo>()
                               .Distinct(new EnumSerializationInfo.EqualityComparer());

            if (!args.Any()) return;

            Generate(builder, typeSymbol, args, generationMode);
        }
        catch
        {

        }

        context.AddSource($"{typeSymbol.Name}SerializationExtensions.g.cs", builder.ToString());
    } // private static void Execute (SourceProductionContext, (GeneratorAttributeSyntaxContext Left, bool Right))

    private static EnumSerializationInfo? GetEnumSerializationInfo(AttributeData attribute)
    {
        var args = attribute.ConstructorArguments;
        if (args.Length == 0) return default;
        if (args[0].Value is not INamedTypeSymbol enumType) return default;

        var caseSensitive = true;
        if (attribute.TryGetNamedArgumentValue("CaseSensitive", out bool cs))
            caseSensitive = cs;

        var methods = ExtensionMethods.All;
        if (attribute.TryGetNamedArgumentEnumValue<ExtensionMethods>("Methods", out var m))
            methods = m;

        return new(enumType, caseSensitive, methods);
    } // private static EnumSerializationInfo? GetEnumSerializationInfo (AttributeData)

    private static void Generate(StringBuilder builder, INamedTypeSymbol enumType, IEnumerable<EnumSerializationInfo> targetTypes, GenerationMode mode)
    {
        var usePooled = false;

        if (targetTypes.All(t => t.ExtensionMethods == ExtensionMethods.None))
            return;

        var enumShortName = enumType.Name;
        var enumName = enumType.GetFullyQualifiedName();

        var ns = enumType.ContainingNamespace.ToDisplayString();

        builder.Append($$"""

namespace {{ns}}
{
    /// <summary>
    /// Provides extension methods for serialization of the <see cref="{{enumName}}"/> enum.
    /// </summary>
    internal static class {{enumShortName}}SerializationExtensions
    {
""");

        var hasToString = targetTypes.Any(t => t.GenerateToString);
        if (hasToString)
            GenerateToString(builder, enumType, targetTypes, mode);

        #region TryParse

        var hasTryParse = targetTypes.Any(t => t.GenerateTryParse);
        if (hasTryParse)
            GenerateTryParse(builder, enumType, targetTypes, mode, out usePooled);

        #endregion TryParse

        builder.AppendLine("""
    }
}
""");

        var canUseFileScoped = mode >= GenerationMode.OptimizedSpanWithPatternMatching;
        if (usePooled && canUseFileScoped)
            builder.AppendLine(PooledBufferSource);
    } // private static void Generate (StringBuilder, INamedTypeSymbol, IEnumerable<INamedTypeSymbol>)

    #region buffer

    // lang=C#
    private const string PooledBufferSource = """

namespace EnumSerializer
{
    /// <summary>
    /// Provides a buffer of a specified length that is rented from a shared array pool and released when disposed.
    /// </summary>
    file ref struct PooledBuffer
    {
        private readonly int _length;
        private char[]? _buffer = null;

        /// <summary>
        /// Initializes a new instance of the <see cref="global::EnumSerializer.PooledBuffer"/> struct with the specified length.
        /// </summary>
        /// <param name="length">The size of the buffer, in bytes.</param>
        /// <remarks>
        /// The buffer is not allocated (or rented) at this point.
        /// It is allocated (or rented) when <see cref="GetSpan"/> is called for the first time.
        /// </remarks>
        internal PooledBuffer(int length)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNegativeOrZero(length, nameof(length));
            this._length = length;
        }

        /// <summary>
        /// Returns a span representing the valid portion of the underlying buffer.
        /// </summary>
        /// <returns>A <see cref="global::System.Span{char}"/> containing the elements in the buffer up to the current length.</returns>
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal global::System.Span<char> GetSpan()
        {
            this._buffer ??= global::System.Buffers.ArrayPool<char>.Shared.Rent(this._length);
            return global::System.MemoryExtensions.AsSpan(this._buffer, 0, this._length);
        }

        /// <summary>
        /// Releases resources used by the instance and returns the underlying buffer to the shared array pool.
        /// </summary>
        public void Dispose()
        {
            var buffer = this._buffer;
            if (buffer is null) return;
            this._buffer = null;
            global::System.Buffers.ArrayPool<char>.Shared.Return(buffer);
        }
    }
}
""";

    #endregion buffer
} // internal sealed partial class SerializerGenerator : IIncrementalGenerator
