
// (c) 2025-2026 Kazuki Kohzuki

using EnumSerializer.Utils;
using System.Collections.Generic;
using System.Threading;

namespace EnumSerializer.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed partial class SerializerGenerator : IIncrementalGenerator
{
    private const int MaxStackAllocLength = 256;

    private const string AttributeFullName = $"{AttributesGenerator.Namespace}.{AttributesGenerator.EnumSerializableName}";

    private static readonly DiagnosticDescriptor InvalidAttributeInheritance = new(
        id: "ES0001",
        title: "Invalid parameter inheritance",
        messageFormat: "Type '{0}' does not inherit from 'EnumSerializer.SerializeValueAttribute'",
        category: "Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    private static readonly DiagnosticDescriptor NoMethodToGenerate = new(
        id: "ES1001",
        title: "No methods to generate",
        messageFormat: "'ExtensionMethods.None' is specified for '{0}'. No extension methods will be generated.",
        category: "Usage",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true
    );

    private static readonly DiagnosticDescriptor MultipleAttribute = new(
        id: "ES1002",
        title: "Duplicate attribute",
        messageFormat: "Multiple '{0}' attributes are applied. This will be ignored.",
        category: "Usage",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault : true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var canUseSpanProvider = context.CompilationProvider.Select(CheckFeaturesAvailability);

        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            static (node, token) => node is EnumDeclarationSyntax,
            static (context, token) => context
        );

        var combined = sources.Combine(canUseSpanProvider);
        context.RegisterSourceOutput(combined, Execute);
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private static GenerationMode CheckFeaturesAvailability(Compilation compilation, CancellationToken cancellationToken)
    {
        if (compilation is not CSharpCompilation csharpCompilation) return GenerationMode.StringFallback;

        // C# 8.0 or later is required for `using` pattern with ref struct
        if (csharpCompilation.LanguageVersion < LanguageVersion.CSharp8) return GenerationMode.StringFallback;

        var readOnlySpanType = compilation.GetTypeByMetadataName("System.ReadOnlySpan`1");
        if (readOnlySpanType == null) return GenerationMode.StringFallback;

        var memoryExtensionsType = compilation.GetTypeByMetadataName("System.MemoryExtensions");
        if (memoryExtensionsType == null) return GenerationMode.StringFallback;

        var hasToLowerInvariantSpan = false;
        foreach (var member in memoryExtensionsType.GetMembers("ToLowerInvariant"))
        {
            if (member is IMethodSymbol method && method.Parameters.Length == 2)
            {
                var p1 = method.Parameters[0].Type.OriginalDefinition;
                var p2 = method.Parameters[1].Type.OriginalDefinition;

                if (p1?.FullyQualifiedName == "global::System.ReadOnlySpan<T>" && p2?.FullyQualifiedName == "global::System.Span<T>")
                {
                    hasToLowerInvariantSpan = true;
                    break;
                }
            }
        }

        if (!hasToLowerInvariantSpan)
            return GenerationMode.StringFallback;

        if (csharpCompilation.LanguageVersion >= LanguageVersion.CSharp14)
            return GenerationMode.ExtensionMember;

        if (csharpCompilation.LanguageVersion >= LanguageVersion.CSharp11)
            return GenerationMode.OptimizedSpanWithPatternMatching;
        
        return GenerationMode.OptimizedSpanWithIfElse;
    } // private static bool CheckFeaturesAvailability (Compilation, CancellationToken)

    private static void Execute(SourceProductionContext context, (GeneratorAttributeSyntaxContext Left, GenerationMode Right) provider)
    {
        var type = provider.Left;
        var generationMode = provider.Right;

        var typeSymbol = (INamedTypeSymbol)type.TargetSymbol;

        var builder = new StringBuilder();
        builder.AppendLine("""
// <auto-generated/>
""");

        if (generationMode >= GenerationMode.OptimizedSpanWithIfElse)
        {
            // C# 8.0 or later
            builder.AppendLine();
            builder.AppendLine("#nullable enable");
        }

        try
        {
            var attrs =
                type.Attributes.Where(a => a.AttributeClass?.FullName == AttributeFullName)
                               .Select(SerializeValueInfo.Create)
                               .OfType<SerializeValueInfo>();

            if (!attrs.Any()) return;

            var targets = new HashSet<SerializeValueInfo>(new SerializeValueInfo.EqualityComparer());
            foreach (var attr in attrs)
            {
                if (!attr.AttributeType.InheritsFrom("global::EnumSerializer.SerializeValueAttribute"))
                {
                    var diagnostic = Diagnostic.Create(
                        descriptor: InvalidAttributeInheritance,
                        location: attr.AttributeLocation,
                        messageArgs: attr.AttributeType.Name
                    );
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                if (attr.ExtensionMethods == ExtensionMethods.None)
                {
                    var diagnostic = Diagnostic.Create(
                        descriptor: NoMethodToGenerate,
                        location: attr.ExtensionMethodsLocation,
                        messageArgs: attr.AttributeType.Name
                    );
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                if (targets.Contains(attr))
                {
                    var diagnostic = Diagnostic.Create(
                        descriptor: MultipleAttribute,
                        location: attr.AttributeLocation,
                        messageArgs: attr.AttributeType.Name
                    );
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                targets.Add(attr);
            }

            if (!targets.Any()) return;

            Generate(builder, typeSymbol, targets, generationMode);
        }
        catch
        {

        }

        context.AddSource($"{typeSymbol.Name}SerializationExtensions.g.cs", builder.ToString());
    } // private static void Execute (SourceProductionContext, (GeneratorAttributeSyntaxContext Left, bool Right))

    private static void Generate(StringBuilder builder, INamedTypeSymbol enumType, IEnumerable<SerializeValueInfo> targetTypes, GenerationMode mode)
    {
        var usePooled = false;

        if (targetTypes.All(t => t.ExtensionMethods == ExtensionMethods.None))
            return;

        var enumShortName = enumType.Name;
        var enumName = enumType.FullyQualifiedName;

        var ns = enumType.ContainingNamespace.ToDisplayString();

        builder.Append($$"""

namespace {{ns}}
{
    /// <summary>
    /// Provides extension methods for serialization of the <see cref="{{enumName}}"/> enum.
    /// </summary>
    internal static class {{enumShortName}}SerializationExtensions
    {
""");

        var hasToString = targetTypes.Any(t => t.GenerateToString);
        if (hasToString)
            GenerateToString(builder, enumType, targetTypes, mode);

        var hasTryParse = targetTypes.Any(t => t.GenerateTryParse);
        if (hasTryParse)
            GenerateTryParse(builder, enumType, targetTypes, mode, out usePooled);

        builder.AppendLine("""
    }
}
""");

        var canUseFileScoped = mode >= GenerationMode.OptimizedSpanWithPatternMatching;
        if (usePooled && canUseFileScoped)
            builder.AppendLine(PooledBufferSource);
    } // private static void Generate (StringBuilder, INamedTypeSymbol, IEnumerable<INamedTypeSymbol>)

    #region buffer

    // lang=C#
    private const string PooledBufferSource = """

namespace EnumSerializer
{
    /// <summary>
    /// Provides a buffer of a specified length that is rented from a shared array pool and released when disposed.
    /// </summary>
    file ref struct PooledBuffer
    {
        private readonly int _length;
        private char[]? _buffer = null;

        /// <summary>
        /// Initializes a new instance of the <see cref="global::EnumSerializer.PooledBuffer"/> struct with the specified length.
        /// </summary>
        /// <param name="length">The size of the buffer, in bytes.</param>
        /// <remarks>
        /// The buffer is not allocated (or rented) at this point.
        /// It is allocated (or rented) when <see cref="GetSpan"/> is called for the first time.
        /// </remarks>
        internal PooledBuffer(int length)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNegativeOrZero(length, nameof(length));
            this._length = length;
        }

        /// <summary>
        /// Returns a span representing the valid portion of the underlying buffer.
        /// </summary>
        /// <returns>A <see cref="global::System.Span{char}"/> containing the elements in the buffer up to the current length.</returns>
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal global::System.Span<char> GetSpan()
        {
            this._buffer ??= global::System.Buffers.ArrayPool<char>.Shared.Rent(this._length);
            return global::System.MemoryExtensions.AsSpan(this._buffer, 0, this._length);
        }

        /// <summary>
        /// Releases resources used by the instance and returns the underlying buffer to the shared array pool.
        /// </summary>
        public void Dispose()
        {
            var buffer = this._buffer;
            if (buffer is null) return;
            this._buffer = null;
            global::System.Buffers.ArrayPool<char>.Shared.Return(buffer);
        }
    }
}
""";

    #endregion buffer
} // internal sealed partial class SerializerGenerator : IIncrementalGenerator
