
// (c) 2026 Kazuki Kohzuki

namespace EnumSerializer.SourceGeneratorUtils;

[Generator(LanguageNames.CSharp)]
internal sealed class DeconstructExtension : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("DeconstructExtension.g.cs", Source));
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    // lang=C#
    private const string Source = """
// <auto-generated/>

namespace EnumSerializer.Utils;

internal static class DeconstructExtension
{
    internal static void Deconstruct<TKey, TValue>(this global::System.Collections.Generic.KeyValuePair<TKey, TValue> pair, out TKey key, out TValue value)
    {
        key = pair.Key;
        value = pair.Value;
    }
}
""";
} // internal sealed class DeconstructExtension : IIncrementalGenerator
