
// (c) 2026 Kazuki Kohzuki

namespace EnumSerializer.SourceGeneratorUtils;

[Generator(LanguageNames.CSharp)]
internal class EmbeddedAttribute : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("EmbeddedAttribute.g.cs", Source));
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    // lang=C#
    private const string Source = """
// <auto-generated/>

namespace Microsoft.CodeAnalysis;

internal sealed class EmbeddedAttribute : global::System.Attribute
{
    internal EmbeddedAttribute() { }
}
""";
} // internal class EmbeddedAttribute : IIncrementalGenerator
