
// (c) 2026 Kazuki Kohzuki

namespace EnumSerializer.SourceGeneratorUtils;

[Generator(LanguageNames.CSharp)]
internal sealed class EquatableArray : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static (context) => context.AddSource("EquatableArray.g.cs", Source));
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    // lang=C#
    private const string Source = """
        // <auto-generated />

        namespace EnumSerializer.Utils;

        /// <summary>
        /// Represents an array of equatable elements that can be compared for equality based on their contents.
        /// </summary>
        /// <typeparam name="T">The type of the elements in the array.</typeparam>
        internal readonly struct EquatableArray<T> : global::System.IEquatable<EquatableArray<T>>, global::System.Collections.Generic.IEnumerable<T> where T : global::System.IEquatable<T>
        {
            private readonly T[] _array;

            /// <summary>
            /// Gets the length of the array.
            /// </summary>
            internal int Length => this._array.Length;

            /// <summary>
            /// Gets the element at the specified index.
            /// </summary>
            /// <param name="index">The zero-based index of the element to get.</param>
            internal ref readonly T this[int index] => ref this._array[index];

            /// <summary>
            /// Initializes a new instance of the <see cref="EquatableArray{T}"/> struct with the specified array.
            /// </summary>
            /// <param name="array">The array to wrap in the <see cref="EquatableArray{T}"/> struct.</param>
            internal EquatableArray(T[] array)
            {
                this._array = array;
            }

            /// <summary>
            /// Returns a span representing the contents of the underlying array.
            /// </summary>
            /// <returns>A <see cref="global::System.Span{T}"/> that provides access to the elements of the underlying array.</returns>
            internal global::System.Span<T> AsSpan()
                => this._array;

            public global::System.Collections.Generic.IEnumerator<T> GetEnumerator()
                => ((global::System.Collections.Generic.IEnumerable<T>)this._array).GetEnumerator();

            global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator()
                => this._array.GetEnumerator();

            public bool Equals(EquatableArray<T> other)
                => global::System.MemoryExtensions.SequenceEqual(AsSpan(), other.AsSpan());

            public static implicit operator EquatableArray<T>(T[] array)
                => new(array);

            public static implicit operator T[](EquatableArray<T> equatableArray)
                => equatableArray._array;
        }
        """;
} // internal sealed class EquatableArray : IIncrementalGenerator