
// (c) 2026 Kazuki Kohzuki

namespace EnumSerializer.SourceGeneratorUtils;

[Generator(LanguageNames.CSharp)]
internal sealed class Range : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("Range.g.cs", Source));
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    // lang=C#
    private const string Source = """
// <auto-generated/>

#nullable enable

namespace System;

/// <summary>
/// Represent a range has start and end indexes.
/// </summary>
/// <remarks>
/// Range is used by the C# compiler to support the range syntax.
/// <code>
/// int[] someArray = new int[5] { 1, 2, 3, 4, 5 };
/// int[] subArray1 = someArray[0..2]; // { 1, 2 }
/// int[] subArray2 = someArray[1..^0]; // { 2, 3, 4, 5 }
/// </code>
/// </remarks>
/// <remarks>Construct a Range object using the start and end indexes.</remarks>
/// <param name="start">Represent the inclusive start index of the range.</param>
/// <param name="end">Represent the exclusive end index of the range.</param>
public readonly struct Range(global::System.Index start, global::System.Index end) : IEquatable<global::System.Range>
{
    /// <summary>
    /// Represent the inclusive start index of the Range.
    /// </summary>
    public global::System.Index Start { get; } = start;

    /// <summary>
    /// Represent the exclusive end index of the Range.
    /// </summary>
    public global::System.Index End { get; } = end;

    /// <summary>
    /// Indicates whether the current Range object is equal to another object of the same type.
    /// </summary>
    /// <param name="value">An object to compare with this object</param>
    override public bool Equals(object? value) =>
        value is Range r &&
        r.Start.Equals(this.Start) &&
        r.End.Equals(this.End);

    /// <summary>
    /// Indicates whether the current Range object is equal to another Range object.
    /// </summary>
    /// <param name="other">An object to compare with this object</param>
    public bool Equals(global::System.Range other) => other.Start.Equals(this.Start) && other.End.Equals(this.End);

    /// <summary>
    /// Returns the hash code for this instance.
    /// </summary>
    override public int GetHashCode()
        => this.Start.GetHashCode() * 31 + this.End.GetHashCode();

    /// <summary>
    /// Converts the value of the current Range object to its equivalent string representation.
    /// </summary>
    override public string ToString()
        => this.Start + ".." + this.End;

    /// <summary>
    /// Create a Range object starting from start index to the end of the collection.
    /// </summary>
    public static global::System.Range StartAt(global::System.Index start) => new(start, global::System.Index.End);

    /// <summary>
    /// Create a Range object starting from first element in the collection to the end Index.
    /// </summary>
    public static global::System.Range EndAt(Index end) => new(global::System.Index.Start, end);

    /// <summary>
    /// Create a Range object starting from first element to the end.
    /// </summary>
    public static global::System.Range All => new(global::System.Index.Start, global::System.Index.End);

    /// <summary>
    /// Calculate the start offset and length of range object using a collection length.
    /// </summary>
    /// <param name="length">The length of the collection that the range will be used with. length has to be a positive value.</param>
    /// <remarks>
    /// For performance reason, we don't validate the input length parameter against negative values.
    /// It is expected Range will be used with collections which always have non negative length/count.
    /// We validate the range is inside the length scope though.
    /// </remarks>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public (int Offset, int Length) GetOffsetAndLength(int length)
    {
        int start;
        var startIndex = this.Start;
        if (startIndex.IsFromEnd)
            start = length - startIndex.Value;
        else
            start = startIndex.Value;

        int end;
        var endIndex = this.End;
        if (endIndex.IsFromEnd)
            end = length - endIndex.Value;
        else
            end = endIndex.Value;

        if ((uint)end > (uint)length || (uint)start > (uint)end)
            throw new ArgumentOutOfRangeException(nameof(length));

        return (start, end - start);
    } // public (int Offset, int Length) GetOffsetAndLength (int)
} // public readonly struct Range : IEquatable<global::System.Range>
""";
}
