
// (c) 2026 Kazuki Kohzuki

namespace EnumSerializer.SourceGeneratorUtils;

[Generator(LanguageNames.CSharp)]
internal sealed class TypeSymbolExtensions : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("TypeSymbolExtensions.g.cs", Source));
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    // lang=C#
    private const string Source = """
// <auto-generated/>

using System.Collections.Generic;

namespace EnumSerializer.Utils;

internal static class TypeSymbolExtensions
{
    extension (global::Microsoft.CodeAnalysis.ITypeSymbol symbol)
    {
        #region name

        /// <summary>
        /// Gets the fully qualified name of the symbol, excluding the global namespace prefix.
        /// </summary>
        internal string FullName
            => symbol.ToDisplayString(global::Microsoft.CodeAnalysis.SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(global::Microsoft.CodeAnalysis.SymbolDisplayGlobalNamespaceStyle.Omitted));

        /// <summary>
        /// Gets the fully qualified name of the symbol, including the global namespace.
        /// </summary>
        internal string FullyQualifiedName
            => symbol.ToDisplayString(global::Microsoft.CodeAnalysis.SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(global::Microsoft.CodeAnalysis.SymbolDisplayGlobalNamespaceStyle.Included));

        #endregion name

        #region inheritance

        internal bool InheritsFrom(string baseTypeFullName)
        {
            var baseType = symbol.BaseType;
            while (baseType is not null)
            {
                if (baseType.FullyQualifiedName == baseTypeFullName) return true;
                baseType = baseType.BaseType;
            }
            return false;
        } // internal bool InheritsFrom (string)

        #endregion inheritance

        internal IEnumerable<global::Microsoft.CodeAnalysis.IFieldSymbol> StaticFields
            => symbol.GetMembers().OfType<global::Microsoft.CodeAnalysis.IFieldSymbol>().Where(f => f.IsStatic);
    }
}
""";
} // internal sealed class TypeSymbolExtensions : IIncrementalGenerator
