// <auto-generated/>

namespace Test
{
    /// <summary>
    /// Provides extension methods for serialization of the <see cref="global::Test.MyEnum"/> enum.
    /// </summary>
    internal static class MyEnumSerializationExtensions
    {
        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToString<TAttr>(this global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
            if (typeof(TAttr) == typeof(global::EnumSerializer.DefaultSerializeValueAttribute))
                return ToDefaultSerializeValue(value);

            // Fallback to default ToString() if no matching attribute type is found
            return value.ToString();
        } // internal static string ToString<TAttr>(this global::Test.MyEnum) where TAttr : global::EnumSerializer.SerializeValueAttribute

        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
        /// </summary>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToDefaultSerializeValue(this global::Test.MyEnum value)
        {
            switch (value)
            {
                case global::Test.MyEnum.Value1:
                    return "val1";
                case global::Test.MyEnum.Value2:
                    return "val2";
                case global::Test.MyEnum.Value3:
                    return "val3";
                default:
                    return value.ToString();
            }
        }
    }
}
