// <auto-generated/>

namespace Test
{
    /// <summary>
    /// Provides extension methods for serialization of the <see cref="global::Test.MyEnum"/> enum.
    /// </summary>
    internal static class MyEnumSerializationExtensions
    {
        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToString<TAttr>(this global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
            if (typeof(TAttr) == typeof(global::EnumSerializer.DefaultSerializeValueAttribute))
                return ToDefaultSerializeValue(value);

            // Fallback to default ToString() if no matching attribute type is found
            return value.ToString();
        } // internal static string ToString<TAttr>(this global::Test.MyEnum) where TAttr : global::EnumSerializer.SerializeValueAttribute

        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
        /// </summary>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToDefaultSerializeValue(this global::Test.MyEnum value)
        {
            switch (value)
            {
                case global::Test.MyEnum.Short:
                    return "Short literal";
                case global::Test.MyEnum.VeryLong:
                    return "An exceptionally elongated string literal meticulously constructed for the explicit purpose of rigorously evaluating the boundary conditions and threshold capacities of high-performance zero-allocation serialization algorithms relying heavily on raw memory manipulation techniques such as ref byte references and span slicing within custom-built Source Generator outputs, specifically intended to trigger dynamic buffer reallocation pathways, aggressively expose potential stack overflow vulnerabilities, and thoroughly validate the robust handling of continuous contiguous memory blocks significantly exceeding the standard two-hundred-and-fifty-six-byte stack-allocated threshold limit without compromising execution speed or introducing hidden garbage collection overhead";
                default:
                    return value.ToString();
            }
        }

        /// <summary>
        /// Deserializes the specified string to a <see cref="global::Test.MyEnum"/> value using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="text">The string representation of the enum value.</param>
        /// <returns>The deserialized <see cref="global::Test.MyEnum"/> value.</returns>
        internal static bool TryParseMyEnum<TAttr>(this string text, out global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
            if (typeof(TAttr) == typeof(global::EnumSerializer.DefaultSerializeValueAttribute))
                return TryParseMyEnumFromDefaultSerializeValue(text, out value);

            // No matching attribute type found
            value = default(global::Test.MyEnum);
            return false;
        }

        /// <summary>
        /// Attempts to deserialize the specified string to a <see cref="global::Test.MyEnum"/> value using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
        /// Comparison is case-insensitive.
        /// </summary>
        /// <param name="text">The string representation of the enum value.</param>
        /// <param name="value">When this method returns, contains the deserialized <see cref="global::Test.MyEnum"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
        /// <returns><see langword="true"/> if the parsing succeeded; otherwise, <see langword="false"/>.</returns>
        internal static bool TryParseMyEnumFromDefaultSerializeValue(this string text, out global::Test.MyEnum value)
        {
            switch (text.Length)
            {
                case 13:
                    if (global::System.String.Equals(text, "Short literal", global::System.StringComparison.OrdinalIgnoreCase))
                    {
                        value = global::Test.MyEnum.Short;
                        return true;
                    }
                    break;
                case 774:
                    if (global::System.String.Equals(text, "An exceptionally elongated string literal meticulously constructed for the explicit purpose of rigorously evaluating the boundary conditions and threshold capacities of high-performance zero-allocation serialization algorithms relying heavily on raw memory manipulation techniques such as ref byte references and span slicing within custom-built Source Generator outputs, specifically intended to trigger dynamic buffer reallocation pathways, aggressively expose potential stack overflow vulnerabilities, and thoroughly validate the robust handling of continuous contiguous memory blocks significantly exceeding the standard two-hundred-and-fifty-six-byte stack-allocated threshold limit without compromising execution speed or introducing hidden garbage collection overhead", global::System.StringComparison.OrdinalIgnoreCase))
                    {
                        value = global::Test.MyEnum.VeryLong;
                        return true;
                    }
                    break;
            }

            value = default(global::Test.MyEnum);
            return false;
        }
    }
}
