// <auto-generated/>

#nullable enable

namespace Test
{
    /// <summary>
    /// Provides extension methods for serialization of the <see cref="global::Test.MyEnum"/> enum.
    /// </summary>
    internal static class MyEnumSerializationExtensions
    {
        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToString<TAttr>(this global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
            if (typeof(TAttr) == typeof(global::EnumSerializer.DefaultSerializeValueAttribute))
                return ToDefaultSerializeValue(value);

            // Fallback to default ToString() if no matching attribute type is found
            return value.ToString();
        } // internal static string ToString<TAttr>(this global::Test.MyEnum) where TAttr : global::EnumSerializer.SerializeValueAttribute

        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
        /// </summary>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToDefaultSerializeValue(this global::Test.MyEnum value)
        {
            return value switch
            {
                global::Test.MyEnum.Short    => "Short literal",
                global::Test.MyEnum.VeryLong => "An exceptionally elongated string literal meticulously constructed for the explicit purpose of rigorously evaluating the boundary conditions and threshold capacities of high-performance zero-allocation serialization algorithms relying heavily on raw memory manipulation techniques such as ref byte references and span slicing within custom-built Source Generator outputs, specifically intended to trigger dynamic buffer reallocation pathways, aggressively expose potential stack overflow vulnerabilities, and thoroughly validate the robust handling of continuous contiguous memory blocks significantly exceeding the standard two-hundred-and-fifty-six-byte stack-allocated threshold limit without compromising execution speed or introducing hidden garbage collection overhead",
                _ => value.ToString(),
            };
        }

        /// <summary>
        /// Deserializes the specified string to a <see cref="global::Test.MyEnum"/> value using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="text">The string representation of the enum value.</param>
        /// <returns>The deserialized <see cref="global::Test.MyEnum"/> value.</returns>
        internal static bool TryParseMyEnum<TAttr>(this global::System.ReadOnlySpan<char> text, out global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
            if (typeof(TAttr) == typeof(global::EnumSerializer.DefaultSerializeValueAttribute))
                return TryParseMyEnumFromDefaultSerializeValue(text, out value);

            // No matching attribute type found
            value = default(global::Test.MyEnum);
            return false;
        }

        /// <summary>
        /// Attempts to deserialize the specified string to a <see cref="global::Test.MyEnum"/> value using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
        /// Comparison is case-insensitive.
        /// </summary>
        /// <param name="text">The string representation of the enum value.</param>
        /// <param name="value">When this method returns, contains the deserialized <see cref="global::Test.MyEnum"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
        /// <returns><see langword="true"/> if the parsing succeeded; otherwise, <see langword="false"/>.</returns>
        internal static bool TryParseMyEnumFromDefaultSerializeValue(this global::System.ReadOnlySpan<char> text, out global::Test.MyEnum value)
        {
            if (text.Length > 774)
            {
                value = default(global::Test.MyEnum);
                return false;
            }

            // `text.Length` may exceed 256 here, so we use pooled buffer to avoid stack overflow in case of very long input
            using global::EnumSerializer.PooledBuffer pooled = new global::EnumSerializer.PooledBuffer(text.Length);
            global::System.Span<char> lowerText = text.Length <= 256 ? stackalloc char[text.Length] : pooled.GetSpan();
            global::System.MemoryExtensions.ToLowerInvariant(text, lowerText);

            switch (lowerText)
            {
                case "short literal":
                    value = global::Test.MyEnum.Short;
                    return true;
                case "an exceptionally elongated string literal meticulously constructed for the explicit purpose of rigorously evaluating the boundary conditions and threshold capacities of high-performance zero-allocation serialization algorithms relying heavily on raw memory manipulation techniques such as ref byte references and span slicing within custom-built source generator outputs, specifically intended to trigger dynamic buffer reallocation pathways, aggressively expose potential stack overflow vulnerabilities, and thoroughly validate the robust handling of continuous contiguous memory blocks significantly exceeding the standard two-hundred-and-fifty-six-byte stack-allocated threshold limit without compromising execution speed or introducing hidden garbage collection overhead":
                    value = global::Test.MyEnum.VeryLong;
                    return true;
            }

            value = default(global::Test.MyEnum);
            return false;
        }

        extension (global::Test.MyEnum)
        {
            /// <summary>
            /// Deserializes the specified string to a <see cref="global::Test.MyEnum"/> value using the specified serialization attribute.
            /// </summary>
            /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
            /// <param name="text">The string representation of the enum value.</param>
            /// <param name="value">When this method returns, contains the deserialized <see cref="global::Test.MyEnum"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
            /// <returns>The deserialized <see cref="global::Test.MyEnum"/> value.</returns>
            internal static bool TryParse<TAttr>(global::System.ReadOnlySpan<char> text, out global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
            {
                return TryParseMyEnum<TAttr>(text, out value);
            }

            /// <summary>
            /// Deserializes the specified string to a <see cref="global::Test.MyEnum"/> value using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
            /// </summary>
            /// <param name="text">The string representation of the enum value.</param>
            /// <param name="value">When this method returns, contains the deserialized <see cref="global::Test.MyEnum"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
            /// <returns><see langword="true"/> if the parsing succeeded; otherwise, <see langword="false"/>.</returns>
            internal static bool TryParseDefaultSerializeValue(global::System.ReadOnlySpan<char> text, out global::Test.MyEnum value)
            {
                return TryParseMyEnumFromDefaultSerializeValue(text, out value);
            }
        }
    }
}

namespace EnumSerializer
{
    /// <summary>
    /// Provides a buffer of a specified length that is rented from a shared array pool and released when disposed.
    /// </summary>
    file ref struct PooledBuffer
    {
        private readonly int _length;
        private char[]? _buffer = null;

        /// <summary>
        /// Initializes a new instance of the <see cref="global::EnumSerializer.PooledBuffer"/> struct with the specified length.
        /// </summary>
        /// <param name="length">The size of the buffer, in bytes.</param>
        /// <remarks>
        /// The buffer is not allocated (or rented) at this point.
        /// It is allocated (or rented) when <see cref="GetSpan"/> is called for the first time.
        /// </remarks>
        internal PooledBuffer(int length)
        {
            global::System.ArgumentOutOfRangeException.ThrowIfNegativeOrZero(length, nameof(length));
            this._length = length;
        }

        /// <summary>
        /// Returns a span representing the valid portion of the underlying buffer.
        /// </summary>
        /// <returns>A <see cref="global::System.Span{char}"/> containing the elements in the buffer up to the current length.</returns>
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal global::System.Span<char> GetSpan()
        {
            this._buffer ??= global::System.Buffers.ArrayPool<char>.Shared.Rent(this._length);
            return global::System.MemoryExtensions.AsSpan(this._buffer, 0, this._length);
        }

        /// <summary>
        /// Releases resources used by the instance and returns the underlying buffer to the shared array pool.
        /// </summary>
        public void Dispose()
        {
            var buffer = this._buffer;
            if (buffer is null) return;
            this._buffer = null;
            global::System.Buffers.ArrayPool<char>.Shared.Return(buffer);
        }
    }
}
