// <auto-generated/>

#nullable enable

namespace Test
{
    /// <summary>
    /// Provides extension methods for serialization of the <see cref="global::Test.MyEnum"/> enum.
    /// </summary>
    internal static class CustomClassName
    {
        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToString<TAttr>(this global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
            if (typeof(TAttr) == typeof(global::EnumSerializer.DefaultSerializeValueAttribute))
                return ToDefaultSerializeValue(value);

            if (typeof(TAttr) == typeof(global::Test.CustomSerializeValueAttribute))
                return ToCustomSerializeValue(value);

            // Fallback to default ToString() if no matching attribute type is found
            return value.ToString();
        } // internal static string ToString<TAttr>(this global::Test.MyEnum) where TAttr : global::EnumSerializer.SerializeValueAttribute

        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
        /// </summary>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToDefaultSerializeValue(this global::Test.MyEnum value)
        {
            return value switch
            {
                global::Test.MyEnum.Value1 => "val1",
                global::Test.MyEnum.Value2 => "val2",
                global::Test.MyEnum.Value3 => "val3",
                _ => value.ToString(),
            };
        }

        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the <see cref="global::Test.CustomSerializeValueAttribute"/> attribute.
        /// </summary>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToCustomSerializeValue(this global::Test.MyEnum value)
        {
            return value switch
            {
                _ => value.ToString(),
            };
        }

        /// <summary>
        /// Deserializes the specified string to a <see cref="global::Test.MyEnum"/> value using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="text">The string representation of the enum value.</param>
        /// <returns>The deserialized <see cref="global::Test.MyEnum"/> value.</returns>
        internal static bool TryParseMyEnum<TAttr>(this global::System.ReadOnlySpan<char> text, out global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
            if (typeof(TAttr) == typeof(global::EnumSerializer.DefaultSerializeValueAttribute))
                return TryParseMyEnumFromDefaultSerializeValue(text, out value);

            if (typeof(TAttr) == typeof(global::Test.CustomSerializeValueAttribute))
                return TryParseMyEnumFromCustomSerializeValue(text, out value);

            // No matching attribute type found
            value = default(global::Test.MyEnum);
            return false;
        }

        /// <summary>
        /// Attempts to deserialize the specified string to a <see cref="global::Test.MyEnum"/> value using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
        /// Comparison is case-sensitive.
        /// </summary>
        /// <param name="text">The string representation of the enum value.</param>
        /// <param name="value">When this method returns, contains the deserialized <see cref="global::Test.MyEnum"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
        /// <returns><see langword="true"/> if the parsing succeeded; otherwise, <see langword="false"/>.</returns>
        internal static bool TryParseMyEnumFromDefaultSerializeValue(this global::System.ReadOnlySpan<char> text, out global::Test.MyEnum value)
        {
            if (text.Length != 4)
            {
                value = default(global::Test.MyEnum);
                return false;
            }

            switch (text)
            {
                case "val1":
                    value = global::Test.MyEnum.Value1;
                    return true;
                case "val2":
                    value = global::Test.MyEnum.Value2;
                    return true;
                case "val3":
                    value = global::Test.MyEnum.Value3;
                    return true;
            }

            value = default(global::Test.MyEnum);
            return false;
        }

        /// <summary>
        /// Attempts to deserialize the specified string to a <see cref="global::Test.MyEnum"/> value using the <see cref="global::Test.CustomSerializeValueAttribute"/> attribute.
        /// </summary>
        /// <param name="text">The string representation of the enum value.</param>
        /// <param name="value">The default value of global::Test.MyEnum.</param>
        /// <returns><see langword="false"/>.</returns>
        /// <remarks>Since there are no enum members decorated with the <see cref="global::Test.CustomSerializeValueAttribute"/> attribute,
        /// this method always returns <see langword="false"/>.</remarks>
        internal static bool TryParseMyEnumFromCustomSerializeValue(this global::System.ReadOnlySpan<char> text, out global::Test.MyEnum value)
        {
            value = default(global::Test.MyEnum);
            return false;
        }

        extension (global::Test.MyEnum)
        {
            /// <summary>
            /// Deserializes the specified string to a <see cref="global::Test.MyEnum"/> value using the specified serialization attribute.
            /// </summary>
            /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
            /// <param name="text">The string representation of the enum value.</param>
            /// <param name="value">When this method returns, contains the deserialized <see cref="global::Test.MyEnum"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
            /// <returns>The deserialized <see cref="global::Test.MyEnum"/> value.</returns>
            internal static bool TryParse<TAttr>(global::System.ReadOnlySpan<char> text, out global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
            {
                return TryParseMyEnum<TAttr>(text, out value);
            }

            /// <summary>
            /// Deserializes the specified string to a <see cref="global::Test.MyEnum"/> value using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
            /// </summary>
            /// <param name="text">The string representation of the enum value.</param>
            /// <param name="value">When this method returns, contains the deserialized <see cref="global::Test.MyEnum"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
            /// <returns><see langword="true"/> if the parsing succeeded; otherwise, <see langword="false"/>.</returns>
            internal static bool TryParseDefaultSerializeValue(global::System.ReadOnlySpan<char> text, out global::Test.MyEnum value)
            {
                return TryParseMyEnumFromDefaultSerializeValue(text, out value);
            }

            /// <summary>
            /// Deserializes the specified string to a <see cref="global::Test.MyEnum"/> value using the <see cref="global::Test.CustomSerializeValueAttribute"/> attribute.
            /// </summary>
            /// <param name="text">The string representation of the enum value.</param>
            /// <param name="value">When this method returns, contains the deserialized <see cref="global::Test.MyEnum"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
            /// <returns><see langword="true"/> if the parsing succeeded; otherwise, <see langword="false"/>.</returns>
            internal static bool TryParseCustomSerializeValue(global::System.ReadOnlySpan<char> text, out global::Test.MyEnum value)
            {
                return TryParseMyEnumFromCustomSerializeValue(text, out value);
            }
        }
    }
}
