// <auto-generated/>

namespace Test
{
    /// <summary>
    /// Provides extension methods for serialization of the <see cref="global::Test.MyEnum"/> enum.
    /// </summary>
    internal static class MyEnumSerializationExtensions
    {
        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToString<TAttr>(this global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
            if (typeof(TAttr) == typeof(global::EnumSerializer.DefaultSerializeValueAttribute))
                return ToDefaultSerializeValue(value);

            // Fallback to default ToString() if no matching attribute type is found
            return value.ToString();
        } // internal static string ToString<TAttr>(this global::Test.MyEnum) where TAttr : global::EnumSerializer.SerializeValueAttribute

        /// <summary>
        /// Serializes the specified <see cref="global::Test.MyEnum"/> value to a string using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
        /// </summary>
        /// <param name="value">The <see cref="global::Test.MyEnum"/> value to serialize.</param>
        /// <returns>The serialized string representation of the enum value.</returns>
        internal static string ToDefaultSerializeValue(this global::Test.MyEnum value)
        {
            switch (value)
            {
                case global::Test.MyEnum.Value1:
                    return "v1";
                case global::Test.MyEnum.Value2:
                    return "val2";
                case global::Test.MyEnum.Value3:
                    return "value3";
                default:
                    return value.ToString();
            }
        }

        /// <summary>
        /// Deserializes the specified string to a <see cref="global::Test.MyEnum"/> value using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="text">The string representation of the enum value.</param>
        /// <returns>The deserialized <see cref="global::Test.MyEnum"/> value.</returns>
        internal static bool TryParseMyEnum<TAttr>(this string text, out global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
            if (typeof(TAttr) == typeof(global::EnumSerializer.DefaultSerializeValueAttribute))
                return TryParseMyEnumFromDefaultSerializeValue(text, out value);

            // No matching attribute type found
            value = default(global::Test.MyEnum);
            return false;
        }

        /// <summary>
        /// Attempts to deserialize the specified string to a <see cref="global::Test.MyEnum"/> value using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
        /// Comparison is case-sensitive.
        /// </summary>
        /// <param name="text">The string representation of the enum value.</param>
        /// <param name="value">When this method returns, contains the deserialized <see cref="global::Test.MyEnum"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
        /// <returns><see langword="true"/> if the parsing succeeded; otherwise, <see langword="false"/>.</returns>
        internal static bool TryParseMyEnumFromDefaultSerializeValue(this string text, out global::Test.MyEnum value)
        {
            switch (text.Length)
            {
                case 2:
                    if (global::System.String.Equals(text, "v1", global::System.StringComparison.Ordinal))
                    {
                        value = global::Test.MyEnum.Value1;
                        return true;
                    }
                    break;
                case 4:
                    if (global::System.String.Equals(text, "val2", global::System.StringComparison.Ordinal))
                    {
                        value = global::Test.MyEnum.Value2;
                        return true;
                    }
                    break;
                case 6:
                    if (global::System.String.Equals(text, "value3", global::System.StringComparison.Ordinal))
                    {
                        value = global::Test.MyEnum.Value3;
                        return true;
                    }
                    break;
            }

            value = default(global::Test.MyEnum);
            return false;
        }
    }
}
