
// (c) 2026 Kazuki Kohzuki

namespace EnumSerializer.TestGenerator.Verify;

[Generator(LanguageNames.CSharp)]
internal sealed class TypesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("VerifyTestAttribute.g.cs", VerifyTestAttributeSource);
            context.AddSource("TestSourceAttribute.g.cs", TestSourceAttributeSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    internal const string Namespace = "EnumSerializer.Test.Verify";
    internal const string VerifyTestAttribute = "VerifyTestAttribute";
    internal const string TestSourceAttribute = "TestSourceAttribute";

    // lang=C#
    private const string VerifyTestAttributeSource = """
// <auto-generated/>
        
#nullable enable

namespace EnumSerializer.Test.Verify;

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
internal sealed class VerifyTestAttribute : global::System.Attribute
{
    internal global::System.Collections.Generic.IReadOnlyList<global::Microsoft.CodeAnalysis.CSharp.LanguageVersion> LanguageVersions { get; }

    internal VerifyTestAttribute(params global::Microsoft.CodeAnalysis.CSharp.LanguageVersion[] languageVersions)
    {
        this.LanguageVersions = languageVersions;
    }
}
""";

    // lang=C#
    private const string TestSourceAttributeSource = """
// <auto-generated/>
        
#nullable enable

namespace EnumSerializer.Test.Verify;

[global::System.AttributeUsage(global::System.AttributeTargets.Field, AllowMultiple = false)]
internal sealed class TestSourceAttribute : global::System.Attribute
{
    public string? TestName { get; set; }

    internal TestSourceAttribute() { }
}
""";
} // internal sealed class TypesGenerator : IIncrementalGenerator
