
// (c) 2026 Kazuki Kohzuki

using EnumSerializer.Utils;
using System.Collections.Immutable;

namespace EnumSerializer.TestGenerator.Verify;

[Generator(LanguageNames.CSharp)]
internal sealed class VerifyTestGenerator : IIncrementalGenerator
{
    private const string RootAttributeFullName = $"{TypesGenerator.Namespace}.{TypesGenerator.VerifyTestAttribute}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            RootAttributeFullName,
            static (node, token) => node is ClassDeclarationSyntax,
            static (context, toekn) => context
        );

        context.RegisterSourceOutput(sources, Execute);
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private static void Execute(SourceProductionContext context, GeneratorAttributeSyntaxContext provider)
    {
        var typeSymbol = (INamedTypeSymbol)provider.TargetSymbol;
        
        var attribute = provider.Attributes.FirstOrDefault(attr => attr.AttributeClass?.FullName == RootAttributeFullName);
        if (attribute is null) return;

        var langVersionArg = attribute.ConstructorArguments[0];
        if (langVersionArg.Kind != TypedConstantKind.Array) return;
        if (langVersionArg.IsNull) return;
        var versions = GetLanguageVersions(langVersionArg.Values).Distinct().ToArray();
        if (versions.Length == 0) return;

        var fields = 
            typeSymbol.GetMembers()
                      .OfType<IFieldSymbol>()
                      .SelectNotNull(TestCaseInfo.FromFieldSymbol)
                      .ToArray();
        if (fields.Length == 0) return;

        var testMethodAttributesBuilder = new StringBuilder("[global::Xunit.Theory]");
        foreach (var version in versions)
        {
            testMethodAttributesBuilder.AppendLine();
            testMethodAttributesBuilder.Append($"    [global::Xunit.InlineData(global::Microsoft.CodeAnalysis.CSharp.LanguageVersion.{version})]");
        }
        var testMethodAttributes = testMethodAttributesBuilder.ToString();

        var ns = typeSymbol.ContainingNamespace.ToDisplayString();

        var builder = new StringBuilder();
        builder.AppendLine($$"""
// <auto-generated/>

namespace {{ns}};

partial class {{typeSymbol.Name}}
{
""");

        foreach (var field in fields)
        {
            var testMethodName = field.GetTestMethodName();
            var testName = testMethodName;

            var directory = Path.GetDirectoryName(field.FilePath) ?? "";
            var snapshotDirectory = Path.Combine(directory, "Snapshots", testName);

            var mod = field.SourceIsStatic ? string.Empty : "this.";
            builder.AppendLine($$"""
                    {{testMethodAttributes}}
                    internal global::System.Threading.Tasks.Task {{ToUniqueMethodName(typeSymbol, testMethodName)}}(global::Microsoft.CodeAnalysis.CSharp.LanguageVersion languageVersion)
                    {
                        return global::{{ns}}.VerifyTestHelper.RunTest({{mod}}{{field.SourceName}}, languageVersion, IgnoreRule, @"{{snapshotDirectory}}");
                    }

                """);
        }

        builder.AppendLine("""
                private static partial bool IgnoreRule(global::Microsoft.CodeAnalysis.GeneratedSourceResult result);
            }
            """);

        builder.AppendLine(HelperSource);

        context.AddSource($"{typeSymbol.Name}.GeneratedTests.g.cs", builder.ToString());
    } // private static void Execute (SourceProductionContext, GeneratorAttributeSyntaxContext)

    private static string ToUniqueMethodName(INamedTypeSymbol typeSymbol, string name)
    {
        if (typeSymbol.GetMembers(name).Length == 0) return name;

        var i = 1;
        string uniqueName;
        while (typeSymbol.GetMembers(uniqueName = $"{name}_{i}").Length > 0)
            ++i;

        return uniqueName;
    } // private static string ToUniqueMethodName (INamedTypeSymbol, string)

    private static IEnumerable<LanguageVersion> GetLanguageVersions(ImmutableArray<TypedConstant> values)
    {
        foreach (var element in values)
        {
            if (element.Value is not int versionValue) continue;
            if (!LanguageVersionCache.IsValid(versionValue)) continue;
            yield return (LanguageVersion)versionValue;
        }
    } // private static IEnumerable<LanguageVersion> GetLanguageVersions (ImmutableArray<TypedConstant>)

    // lang=C#
    private const string HelperSource = """

file static class VerifyTestHelper
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Init()
    {
        global::VerifyTests.VerifySourceGenerators.Initialize();
    } // internal static void Init ()

    private static global::Microsoft.CodeAnalysis.GeneratorDriver GetDriver(string source, global::Microsoft.CodeAnalysis.CSharp.LanguageVersion languageVersion)
    {
        var options = new global::Microsoft.CodeAnalysis.CSharp.CSharpParseOptions(languageVersion);

        var serializerGenerator = new global::EnumSerializer.Generators.SerializerGenerator();
        var attributesGenerator = new global::EnumSerializer.Generators.AttributesGenerator();

        var syntaxTree = global::Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(source, options, cancellationToken: TestContext.Current.CancellationToken);
        var compilation = global::Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(
            assemblyName: "TestComp",
            options: new(global::Microsoft.CodeAnalysis.OutputKind.DynamicallyLinkedLibrary),
            syntaxTrees: [syntaxTree]
        )
            .AddReferences(
                global::Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                global::Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(typeof(global::EnumSerializer.Generators.SerializerGenerator).Assembly.Location)
            );

        return global::Microsoft.CodeAnalysis.CSharp.CSharpGeneratorDriver.Create(attributesGenerator, serializerGenerator)
                                    .WithUpdatedParseOptions(options)
                                    .RunGenerators(compilation, cancellationToken: global::Xunit.TestContext.Current.CancellationToken);
    } // private static GeneratorDriver GetDriver (string, LanguageVersion)

    internal static global::System.Threading.Tasks.Task RunTest(string source, global::Microsoft.CodeAnalysis.CSharp.LanguageVersion languageVersion, global::System.Func<global::Microsoft.CodeAnalysis.GeneratedSourceResult, bool> ignoreRule, string snapshotDirectory)
    {
        var driver = GetDriver(source, languageVersion);
        var results = driver.GetRunResult();
        var targetSource =
            results.Results.SelectMany(r => r.GeneratedSources)
                           .Single(s => !ignoreRule(s))
                           .SourceText.ToString();

        return global::VerifyXunit.Verifier.Verify(target: targetSource, extension: "cs")
                       .UseDirectory(snapshotDirectory)
                       .UseFileName(languageVersion.ToString());
    } // internal static Task RunTest (string, LanguageVersion, Func<GeneratedSourceResult, bool>, string)
} // file static class VerifyTestHelper
""";
} // internal sealed class VerifyTestGenerator : IIncrementalGenerator
