// <auto-generated/>

namespace Test
{
    /// <summary>
    /// Provides extension methods for serialization of the <see cref="global::Test.MyEnum"/> enum.
    /// </summary>
    internal static class MyEnumSerializationExtensions
    {
        /// <summary>
        /// Deserializes the specified string to a <see cref="global::Test.MyEnum"/> value using the specified serialization attribute.
        /// </summary>
        /// <typeparam name="TAttr">The serialization attribute type.</typeparam>
        /// <param name="text">The string representation of the enum value.</param>
        /// <returns>The deserialized <see cref="global::Test.MyEnum"/> value.</returns>
        internal static bool TryParseMyEnum<TAttr>(this string text, out global::Test.MyEnum value) where TAttr : global::EnumSerializer.SerializeValueAttribute
        {
            if (typeof(TAttr) == typeof(global::EnumSerializer.DefaultSerializeValueAttribute))
                return TryParseMyEnumFromDefaultSerializeValue(text, out value);

            // No matching attribute type found
            value = default(global::Test.MyEnum);
            return false;
        }

        /// <summary>
        /// Attempts to deserialize the specified string to a <see cref="global::Test.MyEnum"/> value using the <see cref="global::EnumSerializer.DefaultSerializeValueAttribute"/> attribute.
        /// Comparison is case-sensitive.
        /// </summary>
        /// <param name="text">The string representation of the enum value.</param>
        /// <param name="value">When this method returns, contains the deserialized <see cref="global::Test.MyEnum"/> value if the parsing succeeded, or the default value if the parsing failed.</param>
        /// <returns><see langword="true"/> if the parsing succeeded; otherwise, <see langword="false"/>.</returns>
        internal static bool TryParseMyEnumFromDefaultSerializeValue(this string text, out global::Test.MyEnum value)
        {
            switch (text.Length)
            {
                case 4:
                    if (global::System.String.Equals(text, "val1", global::System.StringComparison.Ordinal))
                    {
                        value = global::Test.MyEnum.Value1;
                        return true;
                    }
                    if (global::System.String.Equals(text, "val2", global::System.StringComparison.Ordinal))
                    {
                        value = global::Test.MyEnum.Value2;
                        return true;
                    }
                    if (global::System.String.Equals(text, "val3", global::System.StringComparison.Ordinal))
                    {
                        value = global::Test.MyEnum.Value3;
                        return true;
                    }
                    break;
            }

            value = default(global::Test.MyEnum);
            return false;
        }
    }
}
