//HintName: EnumSerializableAttribute.g.cs
// <auto-generated/>

#nullable enable

namespace EnumSerializer
{
    /// <summary>
    /// Specifies that the enum is serializable with the specified target attributes.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = false, AllowMultiple = true)]
    internal sealed class EnumSerializableAttribute : global::System.Attribute
    {
        /// <summary>
        /// Gets the target attributes for serialization.
        /// </summary>
        public global::System.Type Target { get; }

        /// <summary>
        /// Gets or sets a value indicating whether the serialization should be case-sensitive.
        /// </summary>
        /// <value><see langword="true"/> if the serialization should be case-sensitive; otherwise, <see langword="false"/>. The default value is <see langword="true"/>.</value>
        public bool CaseSensitive { get; set; } = true;

        /// <summary>
        /// Gets or sets the extension methods to be generated for enum serialization.
        /// </summary>
        public global::EnumSerializer.ExtensionMethods Methods { get; set; } = global::EnumSerializer.ExtensionMethods.All;

        /// <summary>
        /// Initializes a new instance of the <see cref="EnumSerializableAttribute"/> class.
        /// </summary>
        /// <param name="target">Target attribute for serialization.</param>
        internal EnumSerializableAttribute(global::System.Type target)
        {
            this.Target = target;
        }
    }
}
