//HintName: SerializeValueAttribute.g.cs
// <auto-generated/>

#nullable enable

namespace EnumSerializer
{
    /// <summary>
    /// Represents a serialized value of an enum member.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = true)]
    internal abstract class SerializeValueAttribute : global::System.Attribute
    {
        /// <summary>
        /// Gets the serialized value.
        /// </summary>
        internal string Value { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="SerializeValueAttribute"/> class.
        /// </summary>
        /// <param name="value">The serialized value.</param>
        internal SerializeValueAttribute(string value)
        {
            this.Value = value;
        }
    }
}
