//HintName: DefaultSerializeValueAttribute.g.cs
// <auto-generated/>

#nullable enable

namespace EnumSerializer
{
    /// <summary>
    /// Represents a default serialized value of an enum member.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    internal class DefaultSerializeValueAttribute : global::EnumSerializer.SerializeValueAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultSerializeValueAttribute"/> class.
        /// </summary>
        internal DefaultSerializeValueAttribute(string value) : base(value) {}
    }
}
