
// (c) 2026 Kazuki Kohzuki

using EnumSerializer.Utils;

namespace EnumSerializer.TestGenerator.Diagnostics;

[Generator]
internal sealed class DiagnosticTestGenerator : IIncrementalGenerator
{
    private const string RootAttributeFullName = $"{TypesGenerator.Namespace}.{TypesGenerator.DiagnosticTestAttributeName}";
    private const string TestSourceAttributeFullName = $"{TypesGenerator.Namespace}.{TypesGenerator.TestSourceAttributeName}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            RootAttributeFullName,
            static (node, token) => node is ClassDeclarationSyntax,
            static (context, toekn) => context
        );

        context.RegisterSourceOutput(sources, Execute);
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private static void Execute(SourceProductionContext context, GeneratorAttributeSyntaxContext provider)
    {
        var typeSymbol = (INamedTypeSymbol)provider.TargetSymbol;

        var attribute = provider.Attributes.FirstOrDefault(attr => attr.AttributeClass?.FullName == RootAttributeFullName);
        if (attribute is null) return;

        var fields =
            typeSymbol.GetMembers()
                      .OfType<IFieldSymbol>()
                      .Select(ToFieldInfo)
                      .OfType<TestCaseInfo>()
                      .ToArray();
        if (fields.Length == 0) return;

        var ns = typeSymbol.ContainingNamespace.ToDisplayString();

        var builder = new StringBuilder();
        builder.AppendLine($$"""
// <auto-generated/>

namespace {{ns}};

partial class {{typeSymbol.Name}}
{
""");

        foreach (var field in fields)
        {
            var testMethodName = field.GetTestMethodName();

            var mod = field.SourceIsStatic ? string.Empty : "this.";
            builder.AppendLine($$"""

                [global::Xunit.Fact]
                async internal global::System.Threading.Tasks.Task {{testMethodName}}()
                {
                    await new global::{{ns}}.EnumSerializerDiagnosticTest({{mod}}{{field.SourceName}}).RunAsync(global::Xunit.TestContext.Current.CancellationToken);
                }
                """);
        }

        builder.AppendLine("""
            }
            """);

        builder.AppendLine(EnumSerializerDiagnosticTestSource);

        context.AddSource($"{typeSymbol.Name}.GeneratedTests.g.cs", builder.ToString());
    } // private static void Execute (SourceProductionContext, GeneratorAttributeSyntaxContext)

    private static TestCaseInfo? ToFieldInfo(IFieldSymbol field)
    {
        if (field.Type.SpecialType != SpecialType.System_String) return null;

        var attr = field.GetAttributes().FirstOrDefault(attr => attr.AttributeClass?.FullName == TestSourceAttributeFullName);
        if (attr is null) return null;

        if (!attr.TryGetNamedArgumentValue("TestName", out string? testName))
            testName = null;

        if (!IsValidMethodName(testName))
            testName = null; // To avoid creating method with invalid name, we set it to null and use the field name instead.

        var location = field.Locations.FirstOrDefault();
        var filePath = location?.SourceTree?.FilePath ?? "";

        return new(field.Name, field.IsStatic, testName, filePath);
    } // private static FieldInfo? ToFieldInfo (IFieldSymbol)

    private static bool IsValidMethodName(string? name)
    {
        if (string.IsNullOrWhiteSpace(name)) return false;
        if (!SyntaxFacts.IsValidIdentifier(name)) return false;

        if (SyntaxFacts.IsReservedKeyword(SyntaxFacts.GetKeywordKind(name))) return false;
        if (SyntaxFacts.IsContextualKeyword(SyntaxFacts.GetContextualKeywordKind(name))) return false;

        return true;
    } // private static bool IsValidMethodName (string?)

    // lang=C#
    private const string EnumSerializerDiagnosticTestSource = """

        file class EnumSerializerDiagnosticTest : global::Microsoft.CodeAnalysis.CSharp.Testing.CSharpSourceGeneratorTest<
            global::EnumSerializer.Generators.SerializerGenerator,
            global::Microsoft.CodeAnalysis.Testing.DefaultVerifier
        >
        {
            internal EnumSerializerDiagnosticTest(string source)
            {
                this.TestState.Sources.Add(source);
                this.TestState.ReferenceAssemblies = global::Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.Net.Net100;
                this.TestBehaviors = global::Microsoft.CodeAnalysis.Testing.TestBehaviors.SkipGeneratedSourcesCheck;
            }

            override protected global::System.Collections.Generic.IEnumerable<global::System.Type> GetSourceGenerators()
            {
                foreach (var generator in base.GetSourceGenerators())
                    yield return generator;

                yield return typeof(global::EnumSerializer.Generators.AttributesGenerator);
            } // override protected IEnumerable<Type> GetSourceGenerators ()
        } // internal class EnumSerializerDiagnosticTest : DiagnosticTest
        """;
} // internal sealed class DiagnosticTestGenerator : IIncrementalGenerator
